version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - '4000:4000'
    environment:
      - mongodb=mongodb+srv://root:gluten123@cluster0.cdw1p.mongodb.net/gluten?retryWrites=true&w=majority
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=backend:4000
